{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dlmobilecheckoutsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dlmobilecheckoutsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK\/DLMobileCheckout","doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK\/DLMobileCheckoutSDKTheme"]},{"title":"Structures","identifiers":["doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK\/DLCheckoutResult"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"DLMobileCheckoutSDK","title":"DLMobileCheckoutSDK","symbolKind":"module","role":"collection","modules":[{"name":"DLMobileCheckoutSDK"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK/documentation/DLMobileCheckoutSDK/DLMobileCheckoutSDKTheme":{"role":"symbol","title":"DLMobileCheckoutSDKTheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLMobileCheckoutSDKTheme"}],"abstract":[{"type":"text","text":"Defines the theme for the checkout interface. You customize your checkout experience by creating a subclass and overriding the values you want to customize."}],"identifier":"doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK\/DLMobileCheckoutSDKTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLMobileCheckoutSDKTheme"}],"url":"\/documentation\/dlmobilecheckoutsdk\/dlmobilecheckoutsdktheme"},"doc://com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK/documentation/DLMobileCheckoutSDK/DLMobileCheckout":{"role":"symbol","title":"DLMobileCheckout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLMobileCheckout"}],"abstract":[{"type":"text","text":"Entry point for all interactions with the library."}],"identifier":"doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK\/DLMobileCheckout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLMobileCheckout"}],"url":"\/documentation\/dlmobilecheckoutsdk\/dlmobilecheckout"},"doc://com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK/documentation/DLMobileCheckoutSDK/DLCheckoutResult":{"role":"symbol","title":"DLCheckoutResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCheckoutResult"}],"abstract":[{"type":"text","text":"When the checkout process succeeds, this struct will contain all the data generated."}],"identifier":"doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK\/DLCheckoutResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCheckoutResult"}],"url":"\/documentation\/dlmobilecheckoutsdk\/dlcheckoutresult"},"doc://com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK/documentation/DLMobileCheckoutSDK":{"role":"collection","title":"DLMobileCheckoutSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK","kind":"symbol","type":"topic","url":"\/documentation\/dlmobilecheckoutsdk"},"doc://com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK/documentation/DLMobileCheckoutSDK/DLMobileCheckoutSDKVersionNumber":{"role":"symbol","title":"DLMobileCheckoutSDKVersionNumber","fragments":[{"kind":"identifier","text":"DLMobileCheckoutSDKVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for DLMobileCheckoutSDK."}],"identifier":"doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK\/DLMobileCheckoutSDKVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/dlmobilecheckoutsdk\/dlmobilecheckoutsdkversionnumber"},"doc://com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK/documentation/DLMobileCheckoutSDK/DLMobileCheckoutSDKVersionString":{"role":"symbol","title":"DLMobileCheckoutSDKVersionString","fragments":[{"kind":"identifier","text":"DLMobileCheckoutSDKVersionString"}],"abstract":[{"type":"text","text":"Project version string for DLMobileCheckoutSDK."}],"identifier":"doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK\/DLMobileCheckoutSDKVersionString","kind":"symbol","type":"topic","url":"\/documentation\/dlmobilecheckoutsdk\/dlmobilecheckoutsdkversionstring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK\/DLMobileCheckoutSDKVersionNumber","doc:\/\/com.dlocal.DLMobileCheckoutSDK.DLMobileCheckoutSDK\/documentation\/DLMobileCheckoutSDK\/DLMobileCheckoutSDKVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}